typeorm:
  options:
    type: 'mysql'
    host: 'localhost'
    port: 3306
    username: 'root'
    password: '1234'
    database: 'wordhammer_dev'
    synchronize: true
jwt:
  secret: '1234'
